[tool.poetry]
name = "cli"
version = "0.1.0"
description = ""
authors = ["Emily Graber <egragraber@allegheny.edu>"]

[tool.poetry.scripts]
cli = "cli.main:cli_object"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.8.0"
typer = "^0.12.5"
ruff = "^0.6.4"
pymarkdownlnt = "^0.9.23"
taskipy = "^1.13.0"
mypy = "^1.11.2"
pytest = "^8.3.2"

[tool.taskipy.tasks]
ruff = { cmd = "ruff check --preview --output-format=concise cli/main.py ../script/main.py", help = "Run the ruff checks for source code format and linting" }
fix = { cmd = "ruff check --fix", help = "Fix the fixable ruff errors in source code format" }
ruffdetails = { cmd = "ruff check --preview", help = "Run the ruff checks for source code format and linting" }
markdownlint = { cmd = "poetry run pymarkdown --config .pymarkdown.cfg scan ../writing/reflection.md ../README.md", help = "Run the markdown linter on writing" }
mypy = { cmd = "poetry run mypy cli", help = "Run the mypy type checker for potential type errors" }
all = "task ruff && task markdownlint && task mypy && task test"
test = { cmd = "pytest -x -s", help = "Run the pytest test suite" }
test-silent = { cmd = "pytest -x --show-capture=no", help = "Run the pytest test suite without showing output" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
